name: CI/CD Pipeline

on:
  pull_request:
    branches: ["main", "master"]
  push:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: make test

  # build:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: golang:1.22
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Build the app
  #       run: make build

  # lint:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: golangci/golangci-lint:v1.50.0
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Run linters
  #       run: make lint