name: CI/CD Pipeline

on:
  pull_request:
    branches: ["main", "master"]
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Build the app
        run: make build

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest
    # container:
    #   image: golangci/golangci-lint:v1.59.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      # - name: Run linters
      #   run: make lint

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.59.1
          args: -c .golangci.yml -v ./...

